import React from 'react';
import { User, ScoreRecord } from '../../types';
import { ALL_SUBJECTS, CORE_SUBJECTS } from '../../constants';

interface ReportCardProps {
    pupil: User;
    scores: ScoreRecord[];
    mockName: string;
}

export const ReportCard: React.FC<ReportCardProps> = ({ pupil, scores, mockName }) => {
    // Sort scores: Core first, then Electives
    const sortedScores = [...scores].sort((a, b) => {
        const subA = ALL_SUBJECTS.find(s => s.id === a.subjectId);
        const subB = ALL_SUBJECTS.find(s => s.id === b.subjectId);
        if (subA?.type === 'CORE' && subB?.type !== 'CORE') return -1;
        if (subA?.type !== 'CORE' && subB?.type === 'CORE') return 1;
        return 0;
    });

    // Determine Weak Subjects (Grade E8, F9)
    const weakSubjects = scores.filter(s => ['E8', 'F9'].includes(s.grade))
                               .map(s => ALL_SUBJECTS.find(sub => sub.id === s.subjectId)?.name);

    return (
        <div className="bg-white p-8 border border-gray-300 max-w-[210mm] mx-auto mb-8 print-only">
            <div className="text-center border-b-2 border-ubablue pb-4 mb-6">
                <h1 className="text-3xl font-bold text-ubablue uppercase">United Baylor Academy</h1>
                <p className="text-sm text-gray-600">Post Office Box 123, Accra, Ghana | +233 24 350 4091</p>
                <h2 className="text-xl font-bold mt-2 text-ubabrown uppercase">Academic Report Card</h2>
                <div className="flex justify-between mt-4 text-sm font-medium">
                    <span>Pupil: {pupil.firstName} {pupil.lastName}</span>
                    <span>Class: {pupil.classLevel}</span>
                    <span>Exam: {mockName}</span>
                    <span>Date: {new Date().toLocaleDateString()}</span>
                </div>
            </div>

            <table className="w-full border-collapse border border-gray-400 mb-6">
                <thead>
                    <tr className="bg-gray-100">
                        <th className="border border-gray-400 p-2 text-left">Subject</th>
                        <th className="border border-gray-400 p-2 text-center w-20">Score</th>
                        <th className="border border-gray-400 p-2 text-center w-20">Grade</th>
                        <th className="border border-gray-400 p-2 text-left">Remarks / Challenges</th>
                    </tr>
                </thead>
                <tbody>
                    {sortedScores.map(score => {
                        const subject = ALL_SUBJECTS.find(s => s.id === score.subjectId);
                        return (
                            <tr key={score.id} className={score.grade === 'F9' ? 'bg-red-50' : ''}>
                                <td className="border border-gray-400 p-2 font-medium">
                                    {subject?.name} 
                                    {subject?.type === 'CORE' && <span className="text-xs text-gray-500 ml-1">(Core)</span>}
                                </td>
                                <td className="border border-gray-400 p-2 text-center">{score.totalScore}</td>
                                <td className={`border border-gray-400 p-2 text-center font-bold ${score.grade === 'A1' ? 'text-green-700' : ''}`}>
                                    {score.grade}
                                </td>
                                <td className="border border-gray-400 p-2 text-sm text-gray-700">
                                    {score.remarks || "Satisfactory performance."}
                                </td>
                            </tr>
                        );
                    })}
                </tbody>
            </table>

            {weakSubjects.length > 0 && (
                 <div className="mb-6 p-4 bg-yellow-50 border border-yellow-200 rounded">
                    <h4 className="font-bold text-ubabrown text-sm uppercase mb-1">Areas for Improvement</h4>
                    <p className="text-sm">Attention is needed in the following subjects: <b>{weakSubjects.join(', ')}</b>.</p>
                 </div>
            )}

            <div className="grid grid-cols-2 gap-8 mt-12">
                <div className="border-t border-gray-400 pt-2 text-center">
                    <p className="font-bold">Class Facilitator</p>
                    <p className="text-xs text-gray-500 mt-8">(Signature & Date)</p>
                </div>
                <div className="border-t border-gray-400 pt-2 text-center">
                    <p className="font-bold">Head Teacher</p>
                    <p className="text-xs text-gray-500 mt-8">(Signature & Date)</p>
                </div>
            </div>
            
            <div className="mt-8 text-center text-xs text-gray-400">
                Generated by UBA Academic Management System
            </div>
        </div>
    );
};